# Rebuild Data\patch-9.mpq from the files under patch-Z-src\Interface\.
# (Numeric name on purpose: this exe gives lettered patches LOWER priority
# than numbered ones - a patch-Z.mpq loads but loses to patch-4/5.)
# Run from anywhere: powershell -File C:\Users\junk7\WoW\patch-Z-src\build.ps1
# The game must be CLOSED (it holds Data\ archives open on some operations).
$src = $PSScriptRoot
$wow = Split-Path $src
$mpq = Join-Path $env:TEMP "patch-9-build.mpq"
$editor = Join-Path $src "tools\MPQEditor.exe"

# Keep the distribution copy of the addon in sync with the live one.
$liveAddon = Join-Path $wow "Interface\Addons\OctoChallenges"
if (Test-Path $liveAddon) {
    Copy-Item "$liveAddon\OctoChallenges.lua","$liveAddon\OctoChallenges.toc" (Join-Path $src "Addons\OctoChallenges\") -Force
}

# Bake per-character challenge masks from the addon's SavedVariables into
# OctoGlueData.lua (the glue VM has no channel to receive them live).
# Re-run this build after a character's challenges change.
$dataFile = Join-Path $src "Interface\GlueXML\OctoGlueData.lua"
$lines = @("-- Generated by build.ps1 from WTF SavedVariables - do not edit.", "OCTO_BAKED_CHALLENGES = {")
$acctRoot = Join-Path $wow "WTF\Account"
if (Test-Path $acctRoot) {
    Get-ChildItem $acctRoot -Directory | ForEach-Object {
        Get-ChildItem $_.FullName -Directory | Where-Object { $_.Name -ne "SavedVariables" } | ForEach-Object {
            $realm = $_.Name
            Get-ChildItem $_.FullName -Directory | ForEach-Object {
                $sv = Join-Path $_.FullName "SavedVariables\OctoChallenges.lua"
                if (Test-Path $sv) {
                    $m = Select-String -Path $sv -Pattern '\["mask"\]\s*=\s*(\d+)' | Select-Object -First 1
                    if ($m) {
                        $lines += "`t[`"$realm/$($_.Name)`"] = $($m.Matches[0].Groups[1].Value),"
                    }
                }
            }
        }
    }
}
$lines += "}"
Set-Content -Path $dataFile -Value $lines -Encoding ASCII
Write-Host "baked $($lines.Count - 3) challenge entries"

if (Test-Path $mpq) { Remove-Item $mpq -Force }
& $editor n $mpq | Out-Null
Get-ChildItem -Recurse -File (Join-Path $src "Interface") | ForEach-Object {
    $rel = $_.FullName.Substring($src.Length + 1)  # e.g. Interface\GlueXML\CharacterSelect.lua
    & $editor a $mpq $_.FullName $rel | Out-Null
    Write-Host "added $rel"
}
Copy-Item $mpq (Join-Path $wow "Data\patch-9.mpq") -Force
Remove-Item $mpq -Force
Write-Host "installed $(Join-Path $wow 'Data\patch-9.mpq')"
