-- OctoGlue.lua - character-select enhancements for the OctoWoW client.
-- by Krool
--
-- LOADING MECHANISM: this client's exe gives extra patch archives (like our
-- patch-9.mpq) LOWER priority than its built-in patch-1..5 list, so we cannot
-- override patch-4's CharacterSelect.lua directly. Instead patch-9 overrides
-- CreditsFrame.xml (which ships ONLY in the base interface.MPQ, where extras
-- DO win) and that XML includes this file. CreditsFrame.xml sits after
-- CharacterSelect.xml in GlueXML.toc, so by the time this runs the stock
-- functions exist and we can redefine them. XML event handlers call these
-- functions by global name at event time, so redefinition is safe.
--
-- GLUE VM FACTS (established by on-screen diagnostics, 2026-08-23):
--   * CreateFrame and pcall exist; SetCVar/GetCVar DO NOT.
--   * Buttons built purely in Lua do not render; template-inherited ones do
--     (the templates live in our CreditsFrame.xml).
--   * The only persistent, glue-writable storage is the saved account name
--     (Get/SetSavedAccountName -> Config.wtf). "#" is illegal in account
--     names, so the character order is stored as a "#O=..." suffix there and
--     stripped before the login box is filled.
--   * No volume APIs exist in glue - pre-login sound settings would need a
--     DLL and are NOT part of this mod.
--
-- Features:
--   * OctoReorder - per-row up/down arrows to rearrange the character list;
--     order persists via the saved-account-name suffix.
--   * OctoChal    - per-row challenge icons. Data is BAKED at build time
--     from the OctoChallenges addon's SavedVariables (OctoGlueData.lua,
--     generated by build.ps1) - the glue VM has no channel to receive it
--     live. Log a character out and rebuild to refresh.
--   * OctoStatus  - dialog-free ~1s server probe in the top-right corner,
--     auto-run once at the login screen, re-run via the Check Server button.

-- ---------------------------------------------------------------- OctoDiag --
-- On-screen diagnostics. Remove once everything is confirmed working.
local OCTO_VERSION = "v12"
local diagStrings = {}
local diagLines = { "OctoGlue " .. OCTO_VERSION .. " loaded" }

local function Octo_DiagRender()
	local text = table.concat(diagLines, "\n")
	for _, fs in ipairs(diagStrings) do
		fs:SetText(text)
	end
end

local function Octo_Diag(msg)
	if diagLines[table.getn(diagLines)] == msg then
		return -- dedupe repeats (list updates fire often)
	end
	table.insert(diagLines, msg)
	Octo_DiagRender()
end

local function Octo_DiagAttach(parent, point, x, y)
	if parent then
		local fs = parent:CreateFontString(nil, "OVERLAY", "GlueFontNormalSmall")
		fs:SetPoint(point, parent, point, x, y)
		fs:SetTextColor(1, 0.9, 0.3)
		fs:SetJustifyH("LEFT")
		table.insert(diagStrings, fs)
		Octo_DiagRender()
	end
end

local function Octo_Try(label, f, a1, a2)
	if type(pcall) ~= "function" then
		f(a1, a2)
		return true
	end
	local ok, err = pcall(f, a1, a2)
	if not ok then
		Octo_Diag("ERR " .. label .. ": " .. tostring(err))
	end
	return ok
end

Octo_DiagAttach(AccountLoginUI or AccountLogin, "BOTTOM", 0, 45)
Octo_DiagAttach(CharacterSelectUI, "TOPLEFT", 16, -120)

local HAS_SAVEDNAME = type(GetSavedAccountName) == "function"
	and type(SetSavedAccountName) == "function"
Octo_Diag("SavedAccountName " .. (HAS_SAVEDNAME and "ok" or "MISSING")
	.. " / baked " .. (type(OCTO_BAKED_CHALLENGES) == "table" and "ok" or "MISSING"))

-- ------------------------------------------------------- order persistence --
-- The character order lives after a "#" in the saved account name:
--   "Krool#O=Speakno,Kaboom,..."
-- AccountLogin_OnShow (wrapped below) strips the suffix before the login box
-- shows it; AccountLogin_Login re-appends it after the stock save runs.
local memoryOrder = nil -- session fallback when SavedAccountName is missing

local function Order_SplitSaved()
	if not HAS_SAVEDNAME then
		return "", nil
	end
	local s = GetSavedAccountName() or ""
	local i = string.find(s, "#", 1, true)
	if i then
		return string.sub(s, 1, i - 1), string.sub(s, i)
	end
	return s, nil
end

local function Order_GetCSV()
	local _, suffix = Order_SplitSaved()
	if suffix then
		local _, _, csv = string.find(suffix, "^#O=(.*)$")
		if csv and csv ~= "" then
			return csv
		end
	end
	return memoryOrder
end

local function Order_SetCSV(csv)
	memoryOrder = csv
	if not HAS_SAVEDNAME then
		return
	end
	local base = Order_SplitSaved()
	if base == "" and AccountLoginAccountEdit and AccountLoginAccountEdit.GetText then
		base = AccountLoginAccountEdit:GetText() or ""
	end
	SetSavedAccountName(base .. "#O=" .. csv)
end

-- ------------------------------------------------------------ OctoReorder --
-- Renders a display permutation (the server's char-enum order is immutable
-- client-side): ReorderPerm[displaySlot] = server character index.
-- CharacterSelect.selectedIndex stays a SERVER index everywhere (rename,
-- delete, EnterWorld and the selection events keep working untouched); only
-- rendering, row clicks and keyboard navigation translate through the
-- permutation. The create-button path is unaffected: its id is always >
-- numChars, and Reorder_ServerIndex falls back to the input for unmapped
-- ids. The order is saved as names and re-matched by name on every list
-- update, so it survives creates, deletes and renames (unknown names append
-- in server order).
local ReorderPerm = {}

local function Reorder_Save()
	local names = {}
	for slot = 1, GetNumCharacters() do
		local name = GetCharacterInfo(ReorderPerm[slot] or slot)
		if name then
			table.insert(names, name)
		end
	end
	Order_SetCSV(table.concat(names, ","))
end

local function Reorder_Rebuild()
	local numChars = GetNumCharacters()
	ReorderPerm = {}
	local used = {}
	local saved = Order_GetCSV()
	if saved then
		for w in string.gfind(saved, "[^,]+") do
			for i = 1, numChars do
				if not used[i] and GetCharacterInfo(i) == w then
					used[i] = true
					table.insert(ReorderPerm, i)
					break
				end
			end
		end
	end
	for i = 1, numChars do
		if not used[i] then
			table.insert(ReorderPerm, i)
		end
	end
end

local function Reorder_DisplaySlot(serverIndex)
	for slot = 1, table.getn(ReorderPerm) do
		if ReorderPerm[slot] == serverIndex then
			return slot
		end
	end
	return serverIndex
end

local function Reorder_ServerIndex(displaySlot)
	return ReorderPerm[displaySlot] or displaySlot
end

local function Reorder_Move(slot, dir)
	local numChars = GetNumCharacters()
	local other = slot + dir
	if slot < 1 or slot > numChars or other < 1 or other > numChars then
		return
	end
	local t = ReorderPerm[slot]
	ReorderPerm[slot] = ReorderPerm[other]
	ReorderPerm[other] = t
	Reorder_Save()
	PlaySound("gsTitleOptionOK")
	UpdateCharacterList()
end

local reorderArrows = {}

local function Reorder_MakeArrow(slot, parent, dir, yOff)
	local name = "OctoReorder" .. (dir < 0 and "Up" or "Down") .. slot
	-- The stock glue scrollbar button templates provably render at this
	-- screen (every glue scroll frame uses them).
	local template = dir < 0 and "GlueScrollUpButtonTemplate" or "GlueScrollDownButtonTemplate"
	local b = CreateFrame("Button", name, parent, template)
	b:SetWidth(18)
	b:SetHeight(18)
	b:SetPoint("TOPRIGHT", parent, "TOPRIGHT", -3, yOff)
	b:SetFrameLevel(parent:GetFrameLevel() + 2)
	b:SetScript("OnClick", function()
		Reorder_Move(slot, dir)
	end)
	return b
end

local function Reorder_EnsureArrows(slot)
	if not reorderArrows[slot] then
		local parent = _G["CharSelectCharacterButton" .. slot]
		reorderArrows[slot] = {
			up = Reorder_MakeArrow(slot, parent, -1, -6),
			down = Reorder_MakeArrow(slot, parent, 1, -24),
		}
	end
	return reorderArrows[slot]
end

local function Reorder_UpdateArrows(numChars)
	for slot = 1, MAX_CHARACTERS_DISPLAYED do
		if slot <= numChars and numChars > 1 then
			local arrows = Reorder_EnsureArrows(slot)
			if slot > 1 then
				arrows.up:Show()
			else
				arrows.up:Hide()
			end
			if slot < numChars then
				arrows.down:Show()
			else
				arrows.down:Hide()
			end
		elseif reorderArrows[slot] then
			reorderArrows[slot].up:Hide()
			reorderArrows[slot].down:Hide()
		end
	end
end

-- --------------------------------------------------------------- OctoChal --
-- Bit i-1 of the baked mask = entry i below (the server's
-- RESPONSE_PLAYER_CHALLENGES bit order, i.e. Turtle_AvailableChallenges
-- extended by OctoChallengeTip). Names/texts are the stock glue strings.
-- Icons are 16px, up to 7 per row, second row stacking above - fixed size.
local ROW_CHALLENGES = {
	{ icon = "Spell_Nature_TimeStop",              name = CHALLENGE_SLOW_AND_STEADY,  text = CHALLENGE_SLOW_AND_STEADY_TEXT },
	{ icon = "Spell_Nature_Sleep",                 name = CHALLENGE_EXHAUSTION,       text = CHALLENGE_EXHAUSTION_TEXT },
	{ icon = "Ability_DualWield",                  name = CHALLENGE_WAR_MODE,         text = CHALLENGE_WAR_MODE_TEXT },
	{ icon = "INV_Misc_Bone_HumanSkull_01",        name = CHALLENGE_HARDCORE,         text = CHALLENGE_HARDCORE_TEXT },
	{ icon = "Ability_Warrior_Disarm",             name = CHALLENGE_VAGRANT,          text = CHALLENGE_VAGRANT_TEXT },
	{ icon = "Spell_Magic_PolymorphPig",           name = CHALLENGE_BOARING,          text = CHALLENGE_BOARING_TEXT },
	{ icon = "INV_Pet_Mouse",                      name = CHALLENGE_LUNATIC,          text = CHALLENGE_LUNATIC_TEXT },
	{ icon = "Ability_Repair",                     name = CHALLENGE_CRAFTMASTER,      text = CHALLENGE_CRAFTMASTER_TEXT },
	{ icon = "INV_Cask_03",                        name = CHALLENGE_BREWMASTER,       text = CHALLENGE_BREWMASTER_TEXT },
	{ icon = "Ability_Warlock_DemonicEmpowerment", name = CHALLENGE_HEROIC,           text = CHALLENGE_HEROIC_TEXT },
	{ icon = "INV_Sword_41",                       name = CHALLENGE_SAMURAI,          text = CHALLENGE_SAMURAI_TEXT },
	{ icon = "Spell_Holy_PrayerofSpirit",          name = CHALLENGE_TOGETHER_FOREVER, text = CHALLENGE_TOGETHER_FOREVER_TEXT },
	{ icon = "Spell_Shadow_SoulGem",               name = CHALLENGE_TRUE_HARDCORE,    text = CHALLENGE_TRUE_HARDCORE_TEXT },
}

local rowChalIcons = {}

local function Chal_MaskForName(name)
	if type(OCTO_BAKED_CHALLENGES) ~= "table" or not name then
		return nil
	end
	local realm = GetServerName() or ""
	realm = string.gsub(realm, "^%s*(.-)%s*$", "%1")
	return OCTO_BAKED_CHALLENGES[realm .. "/" .. name] or OCTO_BAKED_CHALLENGES[name]
end

local function Chal_EnsureIcon(slot, j)
	rowChalIcons[slot] = rowChalIcons[slot] or {}
	local t = rowChalIcons[slot]
	if not t[j] then
		local parent = _G["CharSelectCharacterButton" .. slot]
		local b = CreateFrame("Button", "OctoChalIcon" .. slot .. "_" .. j, parent, "OctoChalIconTemplate")
		local col = math.mod(j - 1, 7)
		local row = math.floor((j - 1) / 7)
		-- The bottom 15px of each 70px row is hit-rect inset (dead art zone),
		-- so sit above it or the icons look like they belong to the next row.
		b:SetPoint("BOTTOMRIGHT", parent, "BOTTOMRIGHT", -24 - col * 18, 20 + row * 18)
		b:SetFrameLevel(parent:GetFrameLevel() + 2)
		-- Closures over the button rather than `this` (glue handler
		-- convention for `this` in SetScript'd closures is unverified).
		b:SetScript("OnEnter", function()
			if ChallengesTooltip and ChallengesTooltip_Update and b.chalName then
				ChallengesTooltip:ClearAllPoints()
				ChallengesTooltip:SetPoint("TOPRIGHT", b, "TOPLEFT", -10, 0)
				ChallengesTooltip_Update(b.chalName, b.chalText or "")
				ChallengesTooltip:Show()
			end
		end)
		b:SetScript("OnLeave", function()
			if ChallengesTooltip then
				ChallengesTooltip:Hide()
			end
		end)
		t[j] = b
	end
	return t[j]
end

local function Chal_UpdateRow(slot, charName)
	local shown = 0
	local mask = Chal_MaskForName(charName)
	if mask and mask > 0 then
		local bit = 1
		for i = 1, table.getn(ROW_CHALLENGES) do
			if math.mod(mask, bit * 2) >= bit then
				shown = shown + 1
				local b = Chal_EnsureIcon(slot, shown)
				b:SetNormalTexture("Interface\\Icons\\" .. ROW_CHALLENGES[i].icon)
				b.chalName = ROW_CHALLENGES[i].name
				b.chalText = ROW_CHALLENGES[i].text
				b:Show()
			end
			bit = bit * 2
		end
	end
	if rowChalIcons[slot] then
		for j = shown + 1, table.getn(rowChalIcons[slot]) do
			rowChalIcons[slot][j]:Hide()
		end
	end
end

-- Selected-character challenge panel on the LEFT side of the screen:
-- larger icons under a "Challenges" header, refreshed on every selection
-- change.
local selHeader = nil
local selIcons = {}

local function Sel_EnsureHeader()
	if not selHeader and CharacterSelectUI then
		selHeader = CharacterSelectUI:CreateFontString(nil, "OVERLAY", "GlueFontNormalLarge")
		selHeader:SetPoint("TOPLEFT", CharacterSelectUI, "TOPLEFT", 26, -170)
		selHeader:SetText(CHALLENGES or "Challenges")
		selHeader:Hide()
	end
	return selHeader
end

local function Sel_EnsureIcon(j)
	if not selIcons[j] then
		local b = CreateFrame("Button", "OctoSelChal" .. j, CharacterSelectUI, "OctoChalIconTemplate")
		b:SetWidth(32)
		b:SetHeight(32)
		local col = math.mod(j - 1, 4)
		local row = math.floor((j - 1) / 4)
		b:SetPoint("TOPLEFT", CharacterSelectUI, "TOPLEFT", 26 + col * 36, -196 - row * 36)
		b:SetScript("OnEnter", function()
			if ChallengesTooltip and ChallengesTooltip_Update and b.chalName then
				ChallengesTooltip:ClearAllPoints()
				ChallengesTooltip:SetPoint("TOPLEFT", b, "TOPRIGHT", 10, 0)
				ChallengesTooltip_Update(b.chalName, b.chalText or "")
				ChallengesTooltip:Show()
			end
		end)
		b:SetScript("OnLeave", function()
			if ChallengesTooltip then
				ChallengesTooltip:Hide()
			end
		end)
		selIcons[j] = b
	end
	return selIcons[j]
end

local function Sel_Update()
	local shown = 0
	local name = GetCharacterInfo(CharacterSelect.selectedIndex)
	local mask = Chal_MaskForName(name)
	if mask and mask > 0 then
		local bit = 1
		for i = 1, table.getn(ROW_CHALLENGES) do
			if math.mod(mask, bit * 2) >= bit then
				shown = shown + 1
				local b = Sel_EnsureIcon(shown)
				b:SetNormalTexture("Interface\\Icons\\" .. ROW_CHALLENGES[i].icon)
				b.chalName = ROW_CHALLENGES[i].name
				b.chalText = ROW_CHALLENGES[i].text
				b:Show()
			end
			bit = bit * 2
		end
	end
	local h = Sel_EnsureHeader()
	if h then
		if shown > 0 then
			h:Show()
		else
			h:Hide()
		end
	end
	for j = shown + 1, table.getn(selIcons) do
		selIcons[j]:Hide()
	end
end

-- --------------------------- stock function redefinitions ------------------
-- Bodies are patch-4's originals with the marked additions; XML handlers
-- resolve these globals at event time, so redefining here takes effect for
-- every later event.

function CharacterSelect_OnKeyDown()
	if ( arg1 == "ESCAPE" ) then
		CharacterSelect_Exit();
	elseif ( arg1 == "ENTER" ) then
		CharacterSelect_EnterWorld();
	elseif ( arg1 == "PRINTSCREEN" ) then
		Screenshot();
	elseif ( arg1 == "UP" or arg1 == "LEFT" ) then
		-- OctoReorder: navigate in DISPLAY order, not server order.
		local numChars = GetNumCharacters();
		if ( numChars > 1 ) then
			local pos = Reorder_DisplaySlot(this.selectedIndex);
			if ( pos > 1 ) then
				pos = pos - 1;
			else
				pos = numChars;
			end
			CharacterSelect_SelectCharacter(Reorder_ServerIndex(pos));
		end
	elseif ( arg1 == "DOWN" or arg1 == "RIGHT" ) then
		-- OctoReorder: navigate in DISPLAY order, not server order.
		local numChars = GetNumCharacters();
		if ( numChars > 1 ) then
			local pos = Reorder_DisplaySlot(this.selectedIndex);
			if ( pos < numChars ) then
				pos = pos + 1;
			else
				pos = 1;
			end
			CharacterSelect_SelectCharacter(Reorder_ServerIndex(pos));
		end
	end
end

function UpdateCharacterSelection()
	for i=1, MAX_CHARACTERS_DISPLAYED, 1 do
		_G["CharSelectCharacterButton"..i]:UnlockHighlight();
	end

	-- OctoReorder: selectedIndex is a server index; highlight its display slot.
	local index = Reorder_DisplaySlot(CharacterSelect.selectedIndex);
	if ( (index > 0) and (index <= MAX_CHARACTERS_DISPLAYED) )then
		_G["CharSelectCharacterButton"..index]:LockHighlight();
	end

	Octo_Try("sel-chal", Sel_Update); -- OctoChal: left-side panel
end

function UpdateCharacterList()
	local numChars = GetNumCharacters();
	local index = 1;

	Reorder_Rebuild(); -- OctoReorder

	for i=1, numChars, 1 do
		-- OctoReorder: row i shows the character at ReorderPerm[i].
		local name, race, class, level, zone, fileString, gender, ghost = GetCharacterInfo(Reorder_ServerIndex(i));

		local button = _G["CharSelectCharacterButton"..index];
		if ( not name ) then
			button:SetText("ERROR - Tell Jeremy");
		else
			if ( not zone ) then
				zone = "";
			end

			local classColor
			local classToken = TW_CLASS_TOKEN and TW_CLASS_TOKEN[class]
			if classToken and CLASS_COLORS[classToken] then
				classColor = CLASS_COLORS[classToken]
				class = classColor .. class .. "|r"
			end
			_G["CharSelectCharacterButton"..index.."ButtonTextName"]:SetText(name);
			if ( ghost ) then
				_G["CharSelectCharacterButton"..index.."ButtonTextInfo"]:SetText(format(CHARACTER_SELECT_INFO_GHOST, level, class));
			else
				_G["CharSelectCharacterButton"..index.."ButtonTextInfo"]:SetText(format(CHARACTER_SELECT_INFO, level, class));
			end
			_G["CharSelectCharacterButton"..index.."ButtonTextLocation"]:SetText(zone);
		end
		Octo_Try("chal-row", Chal_UpdateRow, index, name); -- OctoChal
		button:Show();

		index = index + 1;
		if ( index > MAX_CHARACTERS_DISPLAYED ) then
			break;
		end
	end

	if ( Octo_Try("arrows", Reorder_UpdateArrows, numChars) ) then
		Octo_Diag("list: " .. numChars .. " chars, arrows ok"); -- OctoReorder
	end

	if ( numChars == 0 ) then
		CharacterSelectDeleteButton:Disable();
		CharSelectEnterWorldButton:Disable();
	else
		CharacterSelectDeleteButton:Enable();
		CharSelectEnterWorldButton:Enable();
	end

	CharacterSelect.createIndex = 0;
	CharSelectCreateCharacterButton:Hide();

	local connected = IsConnectedToServer();
	for i=index, MAX_CHARACTERS_DISPLAYED, 1 do
		local button = _G["CharSelectCharacterButton"..index];
		if ( (CharacterSelect.createIndex == 0) and (numChars < MAX_CHARACTERS_PER_REALM) ) then
			CharacterSelect.createIndex = index;
			if ( connected ) then
				--If can create characters position and show the create button
				CharSelectCreateCharacterButton:SetID(index);
				CharSelectCreateCharacterButton:Show();
			end
		end
		button:Hide();
		index = index + 1;
	end

	if ( numChars == 0 ) then
		CharacterSelect.selectedIndex = 0;
		return;
	end

	if ( CharacterSelect.selectLast == 1 ) then
		CharacterSelect.selectLast = 0;
		CharacterSelect_SelectCharacter(numChars, 1);
		return;
	end

	if ( (CharacterSelect.selectedIndex == 0) or (CharacterSelect.selectedIndex > numChars) ) then
		CharacterSelect.selectedIndex = 1;
	end
	CharacterSelect_SelectCharacter(CharacterSelect.selectedIndex, 1);
end

function CharacterSelectButton_OnClick()
	-- OctoReorder: the button id is a display slot; map it to a server index.
	local id = Reorder_ServerIndex(this:GetID());
	if ( id ~= CharacterSelect.selectedIndex ) then
		CharacterSelect_SelectCharacter(id);
	end
end

function CharacterSelectButton_OnDoubleClick()
	-- OctoReorder: the button id is a display slot; map it to a server index.
	local id = Reorder_ServerIndex(this:GetID());
	if ( id ~= CharacterSelect.selectedIndex ) then
		CharacterSelect_SelectCharacter(id);
	end
	CharacterSelect_EnterWorld();
end

-- ------------------------------------------------------------- OctoStatus --
-- Quick "ping" in the top-right corner: connect with a throwaway account,
-- judge by what comes back and how fast. A connection failure or silence
-- past the timeout means down; an auth-level rejection means the server
-- answered, so it is up. ALL dialogs are swallowed while probing.
local statusBanner = nil
local probing = false

local DOWN_MESSAGES = {}
for _, s in ipairs({ LOGIN_FAILED, LOGIN_SERVER_DOWN, SERVER_DOWN,
		DISCONNECTED, RESPONSE_DISCONNECTED, CHAR_LOGIN_FAILED }) do
	DOWN_MESSAGES[s] = true
end

local UP_MESSAGES = {}
for _, s in ipairs({ LOGIN_UNKNOWN_ACCOUNT, LOGIN_INCORRECT_PASSWORD,
		LOGIN_BANNED, LOGIN_SUSPENDED, LOGIN_ALREADYONLINE, LOGIN_DBBUSY,
		LOGIN_BADVERSION, LOGIN_NOTIME }) do
	UP_MESSAGES[s] = true
end

local function Status_Parent()
	return AccountLoginUI or AccountLogin
end

local function Status_EnsureBanner()
	if not statusBanner then
		statusBanner = Status_Parent():CreateFontString("OctoStatusBanner", "OVERLAY", "GlueFontNormalLarge")
		statusBanner:SetPoint("TOPRIGHT", Status_Parent(), "TOPRIGHT", -20, -20)
		statusBanner:SetJustifyH("RIGHT")
		statusBanner:Hide()
	end
	return statusBanner
end

local function Status_MarkChecking()
	local b = Status_EnsureBanner()
	b:SetTextColor(1, 0.82, 0)
	b:SetText("Checking OctoWoW...")
	b:Show()
end

local function Status_MarkSlow()
	local b = Status_EnsureBanner()
	b:SetTextColor(1, 0.55, 0.1)
	b:SetText("OctoWoW: no answer yet...")
	b:Show()
end

local function Status_MarkDown()
	local b = Status_EnsureBanner()
	b:SetTextColor(1, 0.15, 0.15)
	b:SetText("OctoWoW appears DOWN\n(no answer within 5s)")
	b:Show()
end

local function Status_MarkUp(announce)
	if announce then
		local b = Status_EnsureBanner()
		b:SetTextColor(0.1, 1, 0.1)
		b:SetText("OctoWoW is UP")
		b:Show()
	elseif statusBanner then
		statusBanner:Hide()
	end
end

-- Two-stage verdict: a full auth handshake takes several round-trips, so a
-- short timeout that ABORTS causes false DOWNs. At the soft mark the banner
-- turns cautionary but the attempt keeps running; only the hard mark
-- declares DOWN and aborts. A late auth answer flips the banner to UP.
-- After the hard abort, `probing` intentionally stays set so late dialogs
-- from the aborted attempt are still swallowed (a real Login click or a
-- verdict clears it).
local PROBE_SOFT = 1.2
local PROBE_HARD = 5.0

local probeTimer = CreateFrame("Frame")
probeTimer.elapsed = 0
probeTimer.softShown = false
probeTimer:Hide()
probeTimer:SetScript("OnUpdate", function()
	if not probing then
		probeTimer:Hide()
		return
	end
	probeTimer.elapsed = probeTimer.elapsed + (arg1 or 0.02)
	if not probeTimer.softShown and probeTimer.elapsed >= PROBE_SOFT then
		probeTimer.softShown = true
		Status_MarkSlow()
	end
	if probeTimer.elapsed >= PROBE_HARD then
		probeTimer:Hide()
		Status_MarkDown()
		if type(DisconnectFromServer) == "function" then
			DisconnectFromServer()
		end
	end
end)

function OctoStatus_Probe()
	probing = true
	probeTimer.elapsed = 0
	probeTimer.softShown = false
	probeTimer:Show()
	Status_MarkChecking()
	DefaultServerLogin("octoprobe", "probe")
end

local Octo_OrigGlueDialog_Show = GlueDialog_Show
function GlueDialog_Show(which, text, data)
	if probing then
		if text and DOWN_MESSAGES[text] then
			probing = false
			probeTimer:Hide()
			Status_MarkDown()
		elseif text and UP_MESSAGES[text] then
			probing = false
			probeTimer:Hide()
			Status_MarkUp(true)
		end
		return -- swallow every dialog during a probe (no Connecting/Cancel)
	end
	if text and DOWN_MESSAGES[text] then
		Status_MarkDown()
	end
	return Octo_OrigGlueDialog_Show(which, text, data)
end

-- Wrap AccountLogin_OnShow: strip the "#O=..." order suffix from the login
-- box, and auto-probe once so the corner status populates by itself.
local autoProbed = false
if type(AccountLogin_OnShow) == "function" then
	local Octo_OrigAccountLogin_OnShow = AccountLogin_OnShow
	function AccountLogin_OnShow()
		Octo_OrigAccountLogin_OnShow()
		if AccountLoginAccountEdit and AccountLoginAccountEdit.GetText then
			local t = AccountLoginAccountEdit:GetText() or ""
			local cut = string.find(t, "#", 1, true)
			if cut then
				AccountLoginAccountEdit:SetText(string.sub(t, 1, cut - 1))
			end
		end
		if not autoProbed then
			autoProbed = true
			OctoStatus_Probe()
		end
	end
end

-- Wrap AccountLogin_Login: end any dangling probe, and re-append the order
-- suffix after the stock code saves (or clears) the plain account name.
if type(AccountLogin_Login) == "function" then
	local Octo_OrigAccountLogin_Login = AccountLogin_Login
	function AccountLogin_Login()
		probing = false
		local _, suffix = Order_SplitSaved()
		Octo_OrigAccountLogin_Login()
		if suffix and HAS_SAVEDNAME then
			local s = GetSavedAccountName() or ""
			if not string.find(s, "#", 1, true) then
				SetSavedAccountName(s .. suffix)
			end
		end
	end
end

local Octo_OrigCharacterSelect_OnShow = CharacterSelect_OnShow
function CharacterSelect_OnShow()
	probing = false
	Status_MarkUp() -- we connected, so the server is up; clear the banner
	return Octo_OrigCharacterSelect_OnShow()
end

Octo_Try("check-btn", function()
	local parent = Status_Parent()
	if parent and not _G["OctoStatusCheckButton"] then
		local b = CreateFrame("Button", "OctoStatusCheckButton", parent, "GlueButtonSmallTemplate")
		b:SetPoint("TOPRIGHT", parent, "TOPRIGHT", -20, -75)
		b:SetFrameLevel(parent:GetFrameLevel() + 2)
		b:SetText("Check Server")
		b:SetScript("OnClick", function()
			OctoStatus_Probe()
		end)
	end
end)
Octo_Diag("status section loaded")
